version: '3'

services:
  web-server:
    build:
      context: ./web-server
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./chrome-profiles:/app/chrome-profiles
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    networks:
      - chrome-network

  chrome-base:
    build:
      context: ./chrome-container
      platforms:
        - linux/amd64
    image: chrome-kiosk
    platform: linux/amd64
    networks:
      - chrome-network

networks:
  chrome-network:
    driver: bridge

volumes:
  chrome-profiles:
    driver: local 