version: '3'

services:
  web-server:
    build:
      context: ./web-server
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./chrome-profiles:/app/chrome-profiles:rw  # Sử dụng thư mục từ dự án
      - ./web-server:/app:rw  # Mount thư mục source code vào container
    environment:
      - NODE_ENV=development
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: npm run dev  # Sử dụng nodemon trong development mode
    restart: unless-stopped
    networks:
      - chrome-network

networks:
  chrome-network:
    driver: bridge